// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx_LyuLx9CSIomNUCRjwiyJHcE0pPEwBg',
    appId: '1:104547839941:web:b835fce10456acca57a5ac',
    messagingSenderId: '104547839941',
    projectId: 'ia-art-quiz',
    authDomain: 'ia-art-quiz.firebaseapp.com',
    storageBucket: 'ia-art-quiz.appspot.com',
    measurementId: 'G-FKX6GYWZG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzOTwvpwI37BgOMtB9GgyDlArUxKXSrg',
    appId: '1:104547839941:android:df95e2379d559ca557a5ac',
    messagingSenderId: '104547839941',
    projectId: 'ia-art-quiz',
    storageBucket: 'ia-art-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxO8N1iSXPbu3AhmvXggN2Cp4DqVEPy44',
    appId: '1:104547839941:ios:6d11e997fd62acc857a5ac',
    messagingSenderId: '104547839941',
    projectId: 'ia-art-quiz',
    storageBucket: 'ia-art-quiz.appspot.com',
    iosBundleId: 'com.gp4.iaArt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxO8N1iSXPbu3AhmvXggN2Cp4DqVEPy44',
    appId: '1:104547839941:ios:5681df338cf3d33d57a5ac',
    messagingSenderId: '104547839941',
    projectId: 'ia-art-quiz',
    storageBucket: 'ia-art-quiz.appspot.com',
    iosBundleId: 'com.gp4.iaArt.RunnerTests',
  );
}
